//! Build and write the .env configuration file.

use super::providers::Provider;

pub fn build_env(
    provider: &Provider,
    api_key: &str,
    telegram_token: &str,
    slack_token: &str,
    slack_secret: &str,
    persona: &str,
) -> String {
    let mut c = String::from("# Cratos Environment Variables\n");
    c.push_str("# Generated by cratos init\n\n");

    // LLM Provider
    c.push_str("# ===================\n");
    c.push_str("# LLM Provider\n");
    c.push_str("# ===================\n");
    if provider.name == "ollama" {
        c.push_str("OLLAMA_BASE_URL=http://localhost:11434\n");
    } else if api_key.is_empty() {
        // CLI auth — API key not needed, using CLI subscription
        c.push_str(&format!(
            "# {}=  (using CLI subscription auth)\n",
            provider.env_var
        ));
    } else {
        c.push_str(&format!("{}={}\n", provider.env_var, api_key));
    }
    c.push_str(&format!("CRATOS_DEFAULT_PROVIDER={}\n", provider.name));

    // Default Persona
    c.push_str("\n# ===================\n");
    c.push_str("# Default Persona\n");
    c.push_str("# ===================\n");
    c.push_str(&format!("CRATOS_DEFAULT_PERSONA={}\n", persona));

    // Telegram
    c.push_str("\n# ===================\n");
    c.push_str("# Telegram\n");
    c.push_str("# ===================\n");
    if telegram_token.is_empty() {
        c.push_str("# TELEGRAM_BOT_TOKEN=your-telegram-bot-token\n");
    } else {
        c.push_str(&format!("TELEGRAM_BOT_TOKEN={}\n", telegram_token));
    }

    // Slack
    c.push_str("\n# ===================\n");
    c.push_str("# Slack\n");
    c.push_str("# ===================\n");
    if slack_token.is_empty() {
        c.push_str("# SLACK_BOT_TOKEN=xoxb-your-slack-bot-token\n");
        c.push_str("# SLACK_SIGNING_SECRET=your-slack-signing-secret\n");
    } else {
        c.push_str(&format!("SLACK_BOT_TOKEN={}\n", slack_token));
        c.push_str(&format!("SLACK_SIGNING_SECRET={}\n", slack_secret));
    }

    // Server
    c.push_str("\n# ===================\n");
    c.push_str("# Server\n");
    c.push_str("# ===================\n");
    c.push_str("HOST=127.0.0.1\n");
    c.push_str("PORT=8090\n");

    // Logging
    c.push_str("\n# ===================\n");
    c.push_str("# Logging\n");
    c.push_str("# ===================\n");
    c.push_str("RUST_LOG=cratos=info,tower_http=info\n");

    c
}
